language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install flake8
  - pip install .

script: make test

deploy:
  provider: pypi
  user: davidszotten
  password:
    secure: Nn4tpP7CAPdqayLFiPUOHrF5XGCr/Wt0FYgaGmA6pURYVIbys7mu29vZpUGQnf0quN9GAVL6pdeAT9D2CwbVn1KFfsgAVHqXvuso5B+pJ5LdjOCzaVFfK2HPci8iaclberx9ZxqlaoWhNI2fJd5mR4c93rc+dcS7jVfNOdfB/LM=
  on:
    tags: true
    repo: davidszotten/pytest-cagoule
